### PR TITLE
Update to 1.19 

### PR DESCRIPTION
**Pull request by thejudge156**
Just some stuff to update to 1.19, nothing that internal needed to be changed, just wanted to add support for the new version.

### CODE REVIEW

**Comment by ManiacGamer156** [comment]
I am the dumbest human on Earth, I knew that lwjgl got updated but I didn't realize that I would need to update the OpenXR bindings accordingly.

**Comment by thejudge156** [comment]
June 7th is my target merge date, as that is when 1.19 releases

**Comment by thejudge156** [comment]
Uhh I was going to update fart into this repo, but I guess I will leave that to you lol

**Comment by Sorenon** [comment]
oh whoops 
yeah I'll do that

**Pull request merged**
